// Los textos de las capturas de la App Store, en español y en inglés (app-store-shots.mjs). Titulares
// cortos, que se lean en la miniatura de la búsqueda: lo que gana quien la usa, no la función. Entre
// asteriscos, lo que va en cursiva y color. La cena es con Carlota (la novia del autor): no cambiarlo.

export const STORE_COPY = {
  es: {
    tabs: { inbox: 'Bandeja', places: 'Lugares' },
    sizing: 'Tamaño según importancia',
    untimed: 'Sin hora',
    phrase: 'Cena con Carlota el viernes a las 9 de la noche',
    // La de la ficha lleva tramo: así la regla de la duración sale marcada.
    detailsPhrase: 'Cena con Carlota el viernes de 9 a 11 de la noche',
    resultTitle: 'Cena con Carlota',
    atTime: 'A la hora',
    sayIt: 'o díctalo',
    now: 'ahora',
    place: 'Mercadona',
    placeBody: 'Comprar pan · Leche y huevos',
    gym: 'Gimnasio',
    gymDetail: '19:00 · 1 de 4 hoy',
    lunch: 'Comida con Ana',
    askBody: '¿Has acabado? · 14:00–15:30',
    askActions: ['Sí, hecha', 'Todavía no'],
    widgets: {
      today: [
        { title: 'Pagar la factura de la luz', overdue: true, detail: 'Ayer', weight: 0.3 },
        { title: 'Comprar pan' },
        { title: 'Preparar la presentación', weight: 0.6 },
        { title: 'Enviar el presupuesto', detail: '12:00' },
      ],
      inbox: [{ title: 'Renovar el DNI' }, { title: 'Comprar flores', weight: 0.6 }, { title: 'Devolver el libro' }],
      routines: [
        { title: 'Gimnasio', emoji: '🏋️' },
        { title: 'Leer 20 min', emoji: '📖' },
        { title: 'Estirar', emoji: '🧘' },
        { title: 'Creatina', emoji: '💊', done: true },
      ],
      siri: '«Apunta en Tasks cena con Carlota mañana a las 9»',
      siriReply: 'Apuntada: Cena con Carlota, mañana 21:00',
    },
    shots: {
      write: {
        kicker: 'Apunta en segundos',
        title: 'Escríbelo *como lo dices*.',
        sub: '«Cena con Carlota el viernes a las 9»: el día, la hora y el aviso salen solos.',
      },
      places: { kicker: 'Avisos por lugar', title: 'Te avisa *donde toca*.', sub: '«Al pasar por Mercadona» y salta al llegar, no antes.' },
      agenda: { kicker: 'Agenda', title: 'Tu día, *de un vistazo*.', sub: 'Lo que tiene hora, en su sitio, y el tiempo libre entre medias.' },
      routines: { kicker: 'Rutinas', title: 'Hábitos *de un toque*.', sub: 'Táchalos desde la pantalla de bloqueo y mira crecer la racha.' },
      widgets: { kicker: 'Widgets y Siri', title: 'Sin *abrir la app*.', sub: 'Hoy, la Bandeja y tus rutinas, a mano. Y Siri apunta por ti.' },
      ask: { kicker: 'Al acabar', title: 'Táchala *desde el aviso*.', sub: 'Cuando termina, te pregunta si ya está. Sin abrir nada.' },
      details: { kicker: 'Detalles', title: 'Todo, *antes de añadir*.', sub: 'Día, hora, duración, avisos e importancia en una sola ficha.' },
      month: { kicker: 'Agenda', title: 'De la semana *al mes*.', sub: 'Tira de los días hacia abajo y salta a cualquier fecha.' },
      importance: { kicker: 'Importancia', title: 'Lo importante, *más grande*.', sub: 'Desliza el número y el título crece. Sin etiquetas ni colores.' },
      private: { kicker: 'Privada', title: 'Tuyas. *Solo tuyas*.', sub: 'Sin cuentas ni anuncios: tus tareas no salen de tu iPhone.' },
    },
  },
  en: {
    tabs: { inbox: 'Inbox', places: 'Places' },
    sizing: 'Size by importance',
    untimed: 'No time',
    phrase: 'Dinner with Carlota on Friday at 9pm',
    detailsPhrase: 'Dinner with Carlota on Friday from 9 to 11pm',
    resultTitle: 'Dinner with Carlota',
    atTime: 'On time',
    sayIt: 'or say it',
    now: 'now',
    place: 'Supermarket',
    placeBody: 'Buy bread · Milk and eggs',
    gym: 'Gym',
    gymDetail: '7:00 PM · 1 of 4 today',
    lunch: 'Lunch with Anna',
    askBody: 'Finished? · 2:00–3:30 PM',
    askActions: ['Yes, done', 'Not yet'],
    widgets: {
      today: [
        { title: 'Pay the electricity bill', overdue: true, detail: 'Yesterday', weight: 0.3 },
        { title: 'Buy bread' },
        { title: 'Prepare the presentation', weight: 0.6 },
        { title: 'Send the quote', detail: '12:00 PM' },
      ],
      inbox: [{ title: 'Renew my passport' }, { title: 'Buy flowers', weight: 0.6 }, { title: 'Return the book' }],
      routines: [
        { title: 'Gym', emoji: '🏋️' },
        { title: 'Read 20 min', emoji: '📖' },
        { title: 'Stretch', emoji: '🧘' },
        { title: 'Creatine', emoji: '💊', done: true },
      ],
      siri: '“Add to Tasks dinner with Carlota tomorrow at 9pm”',
      siriReply: 'Added: Dinner with Carlota, tomorrow 9:00 PM',
    },
    shots: {
      write: {
        kicker: 'Jot it down in seconds',
        title: 'Type it *like you say it*.',
        sub: '“Dinner with Carlota on Friday at 9pm”: the day, time and reminder fill themselves in.',
      },
      places: {
        kicker: 'Location reminders',
        title: 'Reminds you *right there*.',
        sub: '“When I get to the supermarket” pops up as you arrive, not before.',
      },
      agenda: { kicker: 'Agenda', title: 'Your day *at a glance*.', sub: 'Timed things in their place, with your free time in between.' },
      routines: { kicker: 'Routines', title: 'Habits, *one tap away*.', sub: 'Check them off from the Lock Screen and watch your streak grow.' },
      widgets: { kicker: 'Widgets & Siri', title: 'No need to *open it*.', sub: 'Today, Inbox and routines at hand. And Siri adds tasks for you.' },
      ask: { kicker: 'When it ends', title: 'Check it off *from the alert*.', sub: 'When it’s over, it asks if you’re done. Nothing to open.' },
      details: { kicker: 'Details', title: 'Everything, *before adding*.', sub: 'Day, time, duration, reminders and importance in one sheet.' },
      month: { kicker: 'Agenda', title: 'From week *to month*.', sub: 'Pull the days down and jump to any date.' },
      importance: { kicker: 'Importance', title: 'What matters, *bigger*.', sub: 'Slide the number and the title grows. No labels, no colors.' },
      private: { kicker: 'Private', title: 'Yours. *Only yours*.', sub: 'No accounts, no ads: your tasks never leave your iPhone.' },
    },
  },
}
